"""Country master. Population from Eurostat 2024 estimates (millions)."""

COUNTRIES = [
    {"code": "DE", "name": "Germany",     "tz": "Europe/Berlin",   "population": 84_500_000, "has_demand_model": True},
    {"code": "NL", "name": "Netherlands", "tz": "Europe/Amsterdam","population": 17_900_000, "has_demand_model": True},
    {"code": "FR", "name": "France",      "tz": "Europe/Paris",    "population": 68_400_000, "has_demand_model": True},
    {"code": "IT", "name": "Italy",       "tz": "Europe/Rome",     "population": 58_900_000, "has_demand_model": True},
    {"code": "AT", "name": "Austria",     "tz": "Europe/Vienna",   "population":  9_100_000, "has_demand_model": True},
    {"code": "CZ", "name": "Czechia",     "tz": "Europe/Prague",   "population": 10_900_000, "has_demand_model": True},
    {"code": "BE", "name": "Belgium",     "tz": "Europe/Brussels", "population": 11_800_000, "has_demand_model": True},
    {"code": "PL", "name": "Poland",      "tz": "Europe/Warsaw",   "population": 36_800_000, "has_demand_model": True},
    {"code": "ES", "name": "Spain",       "tz": "Europe/Madrid",   "population": 48_600_000, "has_demand_model": True},
    {"code": "SK", "name": "Slovakia",    "tz": "Europe/Bratislava","population": 5_400_000, "has_demand_model": False},
    {"code": "HU", "name": "Hungary",     "tz": "Europe/Budapest", "population":  9_600_000, "has_demand_model": False},
    {"code": "RO", "name": "Romania",     "tz": "Europe/Bucharest","population": 19_000_000, "has_demand_model": False},
    {"code": "BG", "name": "Bulgaria",    "tz": "Europe/Sofia",    "population":  6_400_000, "has_demand_model": False},
    {"code": "GR", "name": "Greece",      "tz": "Europe/Athens",   "population": 10_400_000, "has_demand_model": False},
    {"code": "HR", "name": "Croatia",     "tz": "Europe/Zagreb",   "population":  3_800_000, "has_demand_model": False},
    {"code": "SI", "name": "Slovenia",    "tz": "Europe/Ljubljana","population":  2_100_000, "has_demand_model": False},
    {"code": "DK", "name": "Denmark",     "tz": "Europe/Copenhagen","population": 5_950_000, "has_demand_model": False},
    {"code": "IE", "name": "Ireland",     "tz": "Europe/Dublin",   "population":  5_300_000, "has_demand_model": False},
    {"code": "PT", "name": "Portugal",    "tz": "Europe/Lisbon",   "population": 10_500_000, "has_demand_model": False},
    {"code": "LV", "name": "Latvia",      "tz": "Europe/Riga",     "population":  1_870_000, "has_demand_model": False},
    {"code": "LT", "name": "Lithuania",   "tz": "Europe/Vilnius",  "population":  2_870_000, "has_demand_model": False},
    {"code": "EE", "name": "Estonia",     "tz": "Europe/Tallinn",  "population":  1_370_000, "has_demand_model": False},
    {"code": "FI", "name": "Finland",     "tz": "Europe/Helsinki", "population":  5_580_000, "has_demand_model": False},
    {"code": "UK", "name": "United Kingdom", "tz": "Europe/London", "population": 67_700_000, "has_demand_model": False},
    {"code": "CH", "name": "Switzerland", "tz": "Europe/Zurich",   "population":  8_850_000, "has_demand_model": False},
]
